urlAPI="http://catastro.chiapas.gob.mx/Municipios/api/"
token="Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJSb2wiOiIyIiwiVXN1YXJpb0xvZ2luIjoibXVsdGlwYWdvcy0wNTkiLCJNdW5pY2lwaW9DbGF2ZSI6IjA1OSIsIm5iZiI6MTY4MjA5Mzg4OCwiZXhwIjoxNzAzOTUzMDg4LCJpYXQiOjE2ODIwOTM4ODh9.HUpeGePronFivWhR6Bi0BGU5aurmS31Nof5rhh26DbU"
MunicipioClave='059'
Usuario='multipagos-059'
IdExpress=3038
urlreturn='http://catastro.chiapas.gob.mx/multipagos/confirm.aspx'